### ISSUE TITLE
Use vecs of integers instead of bytes

### ISSUE THREAD

**Issue by richardanaya** [richardanaya/conifer#18]
I feel like one performance gain we could get would be by using vecs of integers instead of bytes.

**Comment by nbrr** [comment]
How so? I guess as long as we have 4 bpp we could do u32.

**Comment by richardanaya** [comment]
This is complete :)

**Comment by nbrr** [comment]
You went a bit too fast [there](https://github.com/richardanaya/conifer/blob/master/src/blit_map.rs#L20) and [there](https://github.com/richardanaya/conifer/blob/master/src/canvas.rs#L87) since canvas.pixels size now match the blitmap size.
